tabu = int(input('QUAL TABUADA DESEJA SABER? '))
print('---------------')
print('{}  x {:2} = {}'.format(1, tabu, tabu*1))
print('{}  x {:2} = {}'.format(2, tabu, tabu*2))
print('{}  x {:2} = {}'.format(3, tabu, tabu*3))
print('{}  x {:2} = {}'.format(4, tabu, tabu*4))
print('{}  x {:2} = {}'.format(5, tabu, tabu*5))
print('{}  x {:2} = {}'.format(6, tabu, tabu*6))
print('{}  x {:2} = {}'.format(7, tabu, tabu*7))
print('{}  x {:2} = {}'.format(8, tabu, tabu*8))
print('{}  x {:2} = {}'.format(9, tabu, tabu*9))
print('{} x {:2} = {}'.format(10, tabu, tabu*10))
print('--------------')